spring: 
  profiles: 
    active:
    - dev
---
spring: 
  profiles: dev  #开发环境 
  application:
    name: microservicecloud-config-atxxxx-dev  
---
spring: 
  profiles: test  #开发环境 
  application:
    name: microservicecloud-config-atxxxx-test
 #必须保存成UTF-8格式
